name: Monitor Itaú Beneficios

on:
  schedule:
    # Corre todos los días a las 09:05 UTC (~06:05 Montevideo)
    - cron: "5 9 * * *"
  workflow_dispatch:

jobs:
  scrape-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r monitor/requirements.txt

      - name: Run scraper
        run: |
          python monitor/scrape.py

      - name: Commit changes (if any)
        run: |
          git config user.name "itau-monitor-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/current.json data/changelog.json web/changes.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update changelog [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

  publish:
    needs: scrape-and-build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
